### PR TITLE
Add failban service

### LINKED ISSUE #227: Consider installing fail2ban on the dropbox

### PR DESCRIPTION
**Pull request by kelson42**
Add fail2ban to Dropbox container image

Fixes #227

### CODE REVIEW

**Review by rgaudin — CHANGES_REQUESTED** [review]
I think we should have an explicit configuration and document how to unblock an IP because this is touchy.

We already have a hardly predictable behavior due to [sshd_config](https://linux.die.net/man/5/sshd_config)'s `MaxStartups` and `MaxSessions`.

Also, should we whitelist Github? 99+% of our usage is via Github Actions. If an action is improperly configured (missing or wrong key), then we'd ban Github action failing all openZIM/Kiwix uploads for a while,

**Comment by kelson42** [comment]
@rgaudin After a while, a few hours if not dozen of minutes, access is anyway restored automatically.

**Comment by rgaudin** [comment]
> @rgaudin After a while, a few hours if not dozen of minutes, access is anyway restored automatically.

Default is 1d AFAIK

**Comment by rgaudin** [comment]
https://github.com/fail2ban/fail2ban/blob/master/config/fail2ban.conf#L75

**Comment by kelson42** [comment]
@rgaudin This is the wrong property. Look at "bantime".

**Comment by rgaudin** [comment]
> @rgaudin This is the wrong property. Look at "bantime".

Right https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L21

**Comment by rgaudin** [comment]
And https://github.com/fail2ban/fail2ban/blob/master/config/jail.conf#L103 of course

**Pull request merged**
